accordion/urls.py
from django.urls import path

from . import views

app_name = 'accordion'

urlpatterns = [
    path('', views.index, name='index'),
]

books/urls.py
from django.urls import path

from . import views

app_name = 'books'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('count_like/<str:book_id>', views.count_like, name="count_like"),
    path('top5/', views.get_top5, name="get_top5")
]

loganlogin/urls.py
from django.urls import path

from . import views

app_name = 'loganlogin'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.registerPage, name="registerPage"),
    path('login/', views.loginPage, name="loginPage"),
    path('logout', views.logoutPage, name='logoutPage')
]

story8/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accordion.urls')),
    path('search_book', include('books.urls')),
    path('story10/', include('loganlogin.urls'))
]

accordion/models.py
from django.db import models

# Create your models here.

books/models.py
from django.db import models

# Create your models here.

class Book(models.Model):
    book_id = models.CharField(max_length=25)
    book_title = models.CharField(max_length=200)
    book_img = models.CharField(max_length=250)
    book_link = models.CharField(max_length=200)
    count_like = models.PositiveIntegerField()
    def __str__(self):
        return self.book_title

loganlogin/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class DataProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    name = models.CharField(max_length=250)
    photo = models.CharField(max_length=420)
    birthDate = models.DateField()
    city = models.CharField(max_length=100)
    def __str__(self):
        return self.name

accordion/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'accordion/index.html')

books/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse
from django.core import serializers
from .models import Book

# Create your views here.

def index(request):
    books = Book.objects.all().order_by("-count_like")[:5]
    return render(request, 'books/index.html', {"books": books})

def add(request):
    if request.method == "POST":
        book_id = request.POST["book_id"]
        try:
            book = Book.objects.get(book_id = book_id)
            book.count_like += 1
            book.save()
        except Exception as e:
            Book.objects.create(
                book_id = request.POST["book_id"],
                book_title = request.POST["book_title"],
                book_img = request.POST["book_img"],
                book_link = request.POST["book_link"],
                count_like = 1
            )
    return redirect("books:index")

def count_like(request, book_id):
    try:
        book = Book.objects.get(book_id = book_id)
        return JsonResponse(
            {"likes" : book.count_like}
        )
    except:
        return JsonResponse(
            {"likes" : 0}
        )    

def get_top5(request):
    books = Book.objects.all().order_by("-count_like")[:5]
    books_list = serializers.serialize('json', books)
    return HttpResponse(books_list, content_type="text/json-comment-filtered")

loganlogin/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .models import DataProfile
# Create your views here.

@login_required(login_url='loganlogin:loginPage')
def index(request):
    user = request.user
    try:
        dataProfile = DataProfile.objects.get(user=user)
        context = {
            'user': user,
            'dataProfile': dataProfile
        }
        return render(request, 'loganlogin/index.html', context)
    except:
        context = {
            'user': user,
        }
        return render(request, 'loganlogin/index.html', context)

def registerPage(request):
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get("username")
            messages.success(request, "Your account created successfully, please login")
            return redirect('loganlogin:loginPage')
    context = {'form':form}
    return render(request, 'loganlogin/register.html', context)

def loginPage(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('loganlogin:index')
        else:
            messages.info(request, 'Username or password is incorrect')
    context = {}
    return render(request, 'loganlogin/login.html', context)

def logoutPage(request):
    logout(request)
    messages.success(request, "Logout successfully")
    return redirect('loganlogin:loginPage')

accordion/templates/accordion/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {% block css %}
    
    {% endblock css %}
    <script
    src="https://code.jquery.com/jquery-3.4.1.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
    crossorigin="anonymous"></script>    
    <title>My Accordion</title>
</head>
<body>
    {% block content%}
    
    {% endblock content%}
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

accordion/templates/accordion/index.html
{% extends 'accordion/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'accordion/css/style.css' %}">
{% endblock css %}
{% block content %}
<div class="wrapper col-12">
    <div class="d-flex flex-column justify-content-start align-items-center py-5 col-lg-8 mx-auto">
        <h1 class="mb-5">Hi, I am <u>Gani</u> !</h1>
        <div class="accordion col-md-10 p-0 mt-2 accordion-1" id="accor1">
            <div class="header d-flex justify-content-between align-items-center">
                <h2 class="pl-4 py-2 title col-9 mb-0">Introduction</h2>
                <div class="buttons d-flex justify-content-end justify-content-end col-3 p-0">
                    <div class="up p-2 d-flex align-items-center justify-content-center col-6"><h2>&uarr;</h2></div>
                    <div class="down p-2 d-flex align-items-center justify-content-center col-6"><h2>&darr;</h2></div>
                </div>
            </div>
            <div class="content">
                <p class="px-4 py-3 m-0">Hi, I’m Gani Ilham Irsyadi - a student in the Faculty of Computer Science at University of Indonesia.</p>
                <p class="px-4 py-3 m-0">I create hand-coded websites and web applications for my clients. Interested?</p>
            </div>
        </div>
        <div class="accordion col-md-10 p-0 mt-2 accordion-2" id="accor2">
            <div class="header d-flex justify-content-between align-items-center">
                <h2 class="pl-4 py-2 title col-9 mb-0">Current Activities</h2>
                <div class="buttons d-flex justify-content-end col-3 p-0">
                    <div class="up p-2 d-flex align-items-center justify-content-center col-6"><h2>&uarr;</h2></div>
                    <div class="down p-2 d-flex align-items-center justify-content-center col-6"><h2>&darr;</h2></div>
                </div>
            </div>
            <div class="content">
                <div class="px-4 py-3 m-0">
                    <p>Just staying at home because of this outbreak. I am also:</p>
                    <ul class="m-0">
                        <li>Doing online Learning</li>
                        <li>Working on some projects</li>
                        <li>Cycling once / twice a week</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="accordion col-md-10 p-0 mt-2 accordion-3" id="accor3">
            <div class="header d-flex justify-content-between align-items-center">
                <h2 class="pl-4 py-2 title col-9 mb-0">Experiences</h2>
                <div class="buttons d-flex justify-content-end col-3 p-0">
                    <div class="up p-2 d-flex align-items-center justify-content-center col-6"><h2>&uarr;</h2></div>
                    <div class="down p-2 d-flex align-items-center justify-content-center col-6"><h2>&darr;</h2></div>
                </div>
            </div>
            <div class="content">
                <div class="px-4 py-3 m-0">
                    <ul class="m-0">
                        <li>Web Developer at Pesta Rakyat Komputer event</li>
                        <li>Staff at BEM Fakultas Ilmu Komputer Universitas Indonesia</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="accordion col-md-10 p-0 mt-2 accordion-4" id="accor4">
            <div class="header d-flex justify-content-between align-items-center">
                <h2 class="pl-4 py-2 title col-9 mb-0">Achievements</h2>
                <div class="buttons d-flex justify-content-end col-3 p-0">
                    <div class="up p-2 d-flex align-items-center justify-content-center col-6"><h2>&uarr;</h2></div>
                    <div class="down p-2 d-flex align-items-center justify-content-center col-6"><h2>&darr;</h2></div>
                </div>
            </div>
            <div class="content">
                <p class="px-4 py-3 m-0">For me, these are my achievements :</p>
                <div class="px-4 py-3 m-0">
                    <ul class="m-0">
                        <li>Be a Student of Fasilkom</li>
                        <li>Join organitation and comittee while i was in college</li>
                        <li>Make some friends</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="accordion col-md-10 p-0 mt-2 accordion-5" id="accor5">
            <div class="header d-flex justify-content-between align-items-center">
                <h2 class="pl-4 py-2 title col-9 mb-0">Contact Me</h2>
                <div class="buttons d-flex justify-content-end col-3 p-0">
                    <div class="up p-2 d-flex align-items-center justify-content-center col-6"><h2>&uarr;</h2></div>
                    <div class="down p-2 d-flex align-items-center justify-content-center col-6"><h2>&darr;</h2></div>
                </div>
            </div>
            <div class="content">
                <div class="px-4 py-3 m-0 d-flex flex-column">
                    <div class="d-flex">
                        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Instagram_logo_2016.svg/1200px-Instagram_logo_2016.svg.png" height="30" width="30" class="mr-2">
                        <h4><a href="https://www.instagram.com/ganiirsyadi/">Instagram</a></h4> 
                    </div>
                    <div class="d-flex mt-2">
                        <img src="https://www.stickpng.com/assets/images/58e91afdeb97430e81906504.png" height="30" width="30" class="mr-2">
                        <h4><a href="https://www.linkedin.com/in/gani-ilham-irsyadi-a81418184/">LinkedIn</a></h4> 
                    </div>
                </div>
            </div>
        </div>
        <div class="change-theme d-flex align-items-center mt-4">
            <h4 class="mr-2">Dark Mode</h4>
            <input type="checkbox" hidden="hidden" id="theme">
            <label class="switch" for="theme"></label>
        </div>
    </div>
</div>
<script src="{% static 'accordion/js/main.js' %}"></script>
{% endblock content %}

books/templates/books/index.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Meta -->
  <meta name="images" content="{% static 'books/images/' %}">
  <meta name="index" content="{% url 'books:index' %}">
  <meta name="csrf" content="{{ csrf_token }}">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <!-- Personal CSS -->
  <link rel="stylesheet" href="{% static 'books/css/style.css' %}">

  <!-- Google Font -->
  <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@500;600&display=swap" rel="stylesheet">

  <title>Book Search</title>
</head>

<body class="">
  <!-- Modal -->
  <div class="modal fade" id="exampleModalScrollable" tabindex="-1" role="dialog"
    aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalScrollableTitle">Top 5 Favorite Books</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <!-- Ajax Content -->
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  <!-- End of Modal -->
  <div class="container px-md-5 py-5 px-3">
    <a href="{% url 'books:index' %}" class="text-dark text-decoration-none">
    <h2>Search a Book</h2></a>
    <div class="input-group mb-1 col-md-7 px-0">
      <input type="text" class="form-control input-keyword" placeholder="Book's title" aria-label="Book's title"
        aria-describedby="button-addon2">
      <div class="input-group-append">
        <button class="btn btn-outline-secondary btn-search text-dark search-button" type="button" id="button-addon2">
          Search
        </button>
      </div>
    </div>
    <button type="button" class="btn btn-outline-secondary col-md-7 mb-3 btn-modal" data-toggle="modal"
      data-target="#exampleModalScrollable">
      Top 5 Favorite Books
    </button>
    <div class="d-flex flex-column content">
      <div class="d-flex flex-column justify-content-center col-md-7 mt-5">
        <h3 class="text-center px-2">"That's the thing about books. They let you travel without moving your feet."</h3>
      </div>
      <!-- Ajax Content -->
    </div>
  </div>
  <footer class="bg-dark text-center text-white d-flex align-items-center justify-content-center">
    <p class="text-disabled m-0">&copy; 2020 Copyright</p>
  </footer>
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous">
    </script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>
  <!-- Optional JavaScript -->
  <script src="{% static 'books/js/script.js' %}"></script>
</body>

</html>

loganlogin/templates/loganlogin/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {% block css %}
    
    {% endblock css %}
    <script
    src="https://code.jquery.com/jquery-3.4.1.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
    crossorigin="anonymous"></script>    
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    {% block content%}
    
    {% endblock content%}
    {% block js %}
    
    {% endblock js %}
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

loganlogin/templates/loganlogin/index.html
{% extends 'loganlogin/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'loganlogin/style.css' %}">
{% endblock css %}
{% block title %}Home{% endblock title %}
{% block content %}
<div class="wrapper d-flex flex-column justify-content-center align-items-center">
    <div class="box d-flex flex-column justify-content-center align-items-center">
        {% if dataProfile %}
        <img src="{{ dataProfile.photo }}" alt="" width="100" height="100" class="mb-3">
        <h3>{{ dataProfile.name }}</h3>
        <h5>{{ dataProfile.city }}, {{ dataProfile.birthDate }}</h5>
        {% else %}
        <h3>Hello, {{ request.user }}</h3>
        {% endif %}
        <p class="m-0">Thankyou for login to my page</p>
    </div>
    <a href="{% url 'loganlogin:logoutPage' %}">
        <button type="button" class="btn btn-light btn-logout">Logout</button>
    </a>
</div>
{% endblock content %}

loganlogin/templates/loganlogin/login.html
{% extends 'loganlogin/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'loganlogin/register.css' %}">
{% endblock css %}
{% block title %}Login{% endblock title %}
{% block content %}
{% if user.is_authenticated %}
<div class="wrapper d-flex flex-column align-items-center justify-content-center">
    <div class="box d-flex flex-column justify-content-center align-items-center">
        <h4 class="title">You've logged in</h4>
        <a href="{% url 'loganlogin:index' %}">
            <button type="submit" class="btn btn-light btn-auth align-self-center">Back to Home</button>
        </a>
    </div>
</div>
{% else %}
<div class="wrapper d-flex flex-column align-items-center justify-content-center">
    <div class="box d-flex flex-column justify-content-center align-items-center">
        <h4 class="title">Welcome Back,</h4>
        <form action="" method="post" class="d-flex flex-column justify-content-center">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" class="form-control" name="username" autocomplete="username">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <input type="password" class="form-control" name="password" autocomplete="current-password">
            </div>
            {% for message in messages %}
                {% if message.tags == 'info' %}
                    <small class="form-text text-danger form-error mt-0 mb-3">{{ message }}</small> 
                {% endif %}
                {% if message.tags == 'success' %}
                    <small class="form-text text-success form-error mt-0 mb-3">{{ message }}</small> 
                {% endif %}
            {% endfor %}
            <button type="submit" class="btn btn-light btn-auth align-self-center">Login</button>
            <p>Don't have an account? <a href="{% url 'loganlogin:registerPage' %}">Sign Up</a></p>
        </form>
    </div>
</div>
{% endif %}
{% endblock content %}
{% block js %}
<script>
    $("input").addClass("form-control")
    $("input").eq(1).attr("placeholder", 'Username...')
    $("input").eq(2).attr("placeholder", 'Enter Password...')
</script>
{% endblock js %}

loganlogin/templates/loganlogin/register.html
{% extends 'loganlogin/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'loganlogin/register.css' %}">
{% endblock css %}
{% block title %}Register{% endblock title %}
{% block content %}
{% if user.is_authenticated %}
<div class="wrapper d-flex flex-column align-items-center justify-content-center">
  <div class="box d-flex flex-column justify-content-center align-items-center">
      <h4 class="title">You've logged in</h4>
      <a href="{% url 'loganlogin:index' %}">
          <button type="submit" class="btn btn-light btn-auth align-self-center">Back to Home</button>
      </a>
  </div>
</div>
{% else %}
<div class="wrapper d-flex flex-column align-items-center justify-content-center">
    <div class="box d-flex flex-column justify-content-center align-items-center">
        <h4 class="title">Register</h4>
        <form action="" method="post" class="d-flex flex-column justify-content-center">
            {% csrf_token %}
            <div class="form-group">
                <label for="exampleInputEmail1">Username</label>
                {{form.username}}
                <small class="form-text text-danger form-error">{{ form.errors.username }}</small> 
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                {{form.password1}}
                <small class="form-text text-danger form-error">{{ form.errors.password1 }}</small> 
              </div>
              <div class="form-group">
                <label for="exampleInputPassword2">Confirm Your Password</label>
                {{form.password2}}
                <small class="form-text text-danger form-error">{{ form.errors.password2 }}</small> 
              </div>
            <button type="submit" class="btn btn-light btn-auth align-self-center">Register</button>
            <p>Already have an account? <a href="{% url 'loganlogin:loginPage' %}">Sign In</a></p>
        </form>
    </div>
</div>
{% endif %}
{% endblock content %}
{% block js %}
<script>
    $("input").addClass("form-control");
    $("input").eq(1).attr("placeholder", 'Username...');
    $("input").eq(2).attr("placeholder", 'Enter Password...');
    $("input").eq(3).attr("placeholder", 'Re-Enter Password...');
</script>
{% endblock js %}